### ISSUE TITLE
does not build for Android on 0.36

### ISSUE THREAD

**Issue by eksperts** [fusetools/Fuse.Billing.Android#2]
`/build/Android/Preview/app/src/main/java/com/foreign/Fuse/Billing/Android/InAppBillingService.java:23: error: package com.android.vending.billing does not exist`

`/build/Android/Preview/app/src/main/AndroidManifest.xml:81:9-122 Warning:
    Element meta-data#com.google.android.gms.version at AndroidManifest.xml:81:9-122 duplicated with element declared at AndroidManifest.xml:62:9-122`

**Comment by cbaggers** [comment]
Fixed by https://github.com/fusetools/Fuse.Billing.Android/pull/4

**Comment by cbaggers** [comment]
@eksperts thanks for reporting this

**Comment by BeeWarloc** [comment]
Thanks @eksperts and @cbaggers. Guess this can be closed now that https://github.com/fusetools/Fuse.Billing.Android/pull/4 is merged?

**Comment by eksperts** [comment]
Tested, builds fine on Android. Thanks for the fix guys!
